version: "3"
services:
  firefox:
    image: firefox:latest 
    container_name: firefox
#    security_opt:
#      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
#    volumes:
#      - /path/to/config:/config
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped
